### ISSUE TITLE
Configuración del settings.py

### ISSUE THREAD

**Issue by hugoprograma324** [LordChiki18/BANCO_FINAL#11]
### Resumen:

Realizar la configuración necesaria para el settings.py del proyecto.

### Comandos:

pip install django
pip install djangorestframework
pip install djangorestframework-simplejwt

### Objetivos:

- [x] Declarar las aplicaciones Third Party en APPS_INSTALLED (Relacionado con la Issue #9)
- [x] Declarar las aplicaciones propias del proyecto en APPS_INSTALLED (Relacionado con la Issue #9)
- [x] REST_FRAMEWORK_DEFAULT_AUTHORIZATION_CLASS (Relacionado con la Issue #22)
- [x] REST_FRAMEWORK_DEFAULT_AUTHENTICATION_CLASS (Relacionado con la Issue #22)
- [x] Parámetros de DATABASE (Relacionado con la Issue #16)
- [x] Variables de entorno mediante importación os (Relacionado con la Issue #13)
- [x] Configuraciones para la parte del Front (Hugo - Ariel - Jose) (Relacionado con la Issue #10)
