### ISSUE TITLE
Seguridad en el BackEnd

### ISSUE THREAD

**Issue by hugoprograma324** [LordChiki18/BANCO_FINAL#22]
### Resumen:

Realizar la implementacion del rest framework simplejwt para la autentificacion via tokens de los usuarios, la correcta creacion de rutas URL para los tokens y los permisos correspondientes.

### Comandos:

pip install djangorestframework-simplejwt
pip install djangorestframework

### Objetivos:

- [x] Incluir en INSTALLED_APPS el 'rest_framework_simplejwt' (Relacionado con la Issue #11)
- [x] REST_FRAMERWORK  (Relacionado con la Issue #11)
- [x] DEFAULT_PERMISSION_CLASS (Relacionado con la Issue #11)
- [x] DEFAULT_AUTHENTICATION_CLASSES  (Relacionado con la Issue #11)
- [x] SIMPLE_JWT  (Relacionado con la Issue #11)
- [x] Crear los URLS para la generación del token y el token refresh
- [x] Implementar en las vistas permission_classes = [IsAuthenticated] ((Relacionado con la Issue #22))
